version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - LLM_API_URL=${LLM_API_URL}
      - API_KEY=${API_KEY}
    volumes:
      - ./DjangoTest1/chatbot:/app
    depends_on:
      - openwebui

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - ENABLE_API_KEY=true
    # Optionally mount a data folder for model persistence
    # volumes:
    #   - ./local-llm-data:/app/backend/data
